[project]
name = "scene-writer"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "John Hoff",email = "john.hoff@braindonor.net"},
]
dependencies = [
    "sqlalchemy",
    "typer",
    "litellm>=1.97.0",
    "python-dotenv>=1.2.3",
    "textual>=8.2.8",
    "PySide6",
]
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "Apache-2.0"}

[project.scripts]
scene-data = "scene.cli.data:app"
scene-coordinator = "scene.cli.coordinator:app"
scene-writer = "scene.gui.app:main"

[project.optional-dependencies]
dev = [
    "crypts-and-commits @ git+https://github.com/theBraindonor/crypts-and-commits.git#subdirectory=packages/crypts-and-commits",
    "pytest",
    "pytest-cov",
    "ruff",
    "pytest-asyncio>=1.4.0",
    "pytest-qt",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.scripts]
lint = "ruff check ."

[tool.pytest.ini_options]
testpaths = ["test"]
pythonpath = ["src"]
addopts = "--import-mode=importlib --cov=src/scene --cov-report=html --cov-report=term"
asyncio_mode = "auto"

[tool.ruff]
line-length = 120
